---
title: "OBIS dataset licenses"
author: "Pieter Provoost"
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 2
    grid:
      sidebar-width: 300px
      body-width: 1100px
      margin-width: 20px
      gutter-width: 1.5rem
---

# Dataset metadata

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(robis)
library(scales)
library(knitr)
library(stringr)
library(tidyr)

report_theme <- theme(
    axis.text = element_text(colour = "black"),
    axis.line = element_line(linewidth = rel(1)),
    axis.line.y = element_blank(),
    axis.ticks = element_line(), axis.ticks.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    plot.background = element_blank(),
    panel.background = element_rect(fill = "#f5f5f5", colour = NA),
    legend.background = element_blank()
  )
```

```{r message=FALSE}
#| cache: true
full_datasets <- dataset()
```

```{r}
datasets <- full_datasets %>% 
  select(id, records, intellectualrights, node_name, title) %>% 
  mutate(
    license = case_when(
      str_detect(intellectualrights, "CC-BY\\)?[- ]4.0") ~ "CC BY",
      str_detect(intellectualrights, "creativecommons.org/licenses/by/4.0") ~ "CC BY",
      str_detect(intellectualrights, "CC-BY-?NC\\)?[- ]4.0") ~ "CC BY-NC",
      str_detect(intellectualrights, "CC[- ]BY[- ]SA") ~ "CC BY-SA",
      str_detect(intellectualrights, "CC[- ]BY[- ]NC[- ]SA") ~ "CC BY-NC-SA",
      str_detect(intellectualrights, "CC[- ]BY[- ]NC[- ]ND") ~ "CC BY-NC-ND",
      str_detect(intellectualrights, "CC[- ]BY[- ]ND") ~ "CC BY-ND",
      str_detect(intellectualrights, "(?i)CC0") ~ "CC0",
      str_detect(intellectualrights, "waived all rights") ~ "CC0",
      str_detect(intellectualrights, "creativecommons.org/publicdomain/zero/1\\.0") ~ "CC0",
      str_detect(intellectualrights, "Open Data Commons Attribution") ~ "Open Data Commons Attribution",
      str_detect(intellectualrights, "(?i)unrestricted") ~ "CC0",
      str_detect(intellectualrights, "(?i)^restricted") ~ "Restricted",
      str_detect(intellectualrights, "remain property of") ~ "Restricted",
      str_detect(intellectualrights, "data.gc.ca/eng/open-government-licence-canada") ~ "Open Government Licence - Canada",
      str_detect(intellectualrights, "ICES Data Policy") ~ "ICES Data Policy",
      TRUE ~ "Unknown"
    )
  ) %>% mutate(
    intellectualrights = gsub("\\\n", " ", intellectualrights),    
    category = case_when(
      license == "CC0" ~ "CC0",
      license == "CC BY" ~ "CC BY",
      TRUE ~ "Other"
    )
  )
```

# Records and datasets by license

```{r}
licenses <- datasets %>% 
  group_by(license, intellectualrights, category) %>%
  summarise(datasets = n(), records = sum(records), .groups = "drop") %>%
  arrange(desc(records))

kable(licenses %>% head(10))
```

## Number of records

```{r}
#| fig-width: 12
#| fig-height: 7
#| fig.fullwidth: true
license_stats <- licenses %>% 
  group_by(license, category) %>% 
  summarize(records = sum(records), datasets = sum(datasets), .groups = "drop") %>% 
  arrange(-records) %>% 
  mutate(
    license = factor(license, levels = rev(reorder(license, records))),
    category = factor(category, levels = c("CC0", "CC BY", "Other")),
    records_percentage = records / sum(records) * 100,
    datasets_percentage = datasets / sum(datasets) * 100
  )

ggplot(data = license_stats) +
  geom_bar(aes(y = license, x = records, fill = category), stat = "identity") +
  geom_text(aes(y = license, x = records, label = paste0(round(records_percentage, 1), "%")), vjust = 0.5, hjust = -0.2) +
  ggtitle("Licenses by number of records") +
  scale_fill_manual(values = c("#7ABD7E", "#FFB54C", "#FF6961")) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.1)),
    labels = label_comma()
  ) +
  report_theme
```

## Number of datasets

```{r}
#| fig-width: 12
#| fig-height: 7
#| fig.fullwidth: true
ggplot(data = license_stats) +
  geom_bar(aes(y = license, x = datasets, fill = category), stat = "identity") +
  geom_text(aes(y = license, x = datasets, label = paste0(round(datasets_percentage, 1), "%")), vjust = 0.5, hjust = -0.2) +
  ggtitle("Licenses by number of datasets") +
  scale_fill_manual(values = c("#7ABD7E", "#FFB54C", "#FF6961")) +
  scale_x_continuous(
    expand = expansion(mult = c(0, 0.1)),
    labels = label_comma()
  ) +
  report_theme
```

# Records and datasets by node and license

## Number of records

```{r}
#| fig-width: 12
#| fig-height: 9
#| fig.fullwidth: true
node_license_stats <- datasets %>%
  separate_rows(node_name, sep = ",") %>% 
  group_by(node_name, category) %>%
  summarise(datasets = n(), records = sum(records), .groups = "drop") %>% 
  mutate(node_name = factor(node_name, levels = rev(sort(unique(node_name)))))

ggplot(data = node_license_stats) +
  geom_bar(aes(y = node_name, x = records, fill = category), stat = "identity") +
  scale_fill_manual(values = c("#7ABD7E", "#FFB54C", "#FF6961")) +
  scale_x_continuous(
    labels = label_comma()
  ) +
  ylab("node") +
  ggtitle("Number of records by node and license") +
  report_theme
```

## Number of datasets

```{r}
#| fig-width: 12
#| fig-height: 9
#| fig.fullwidth: true
ggplot(data = node_license_stats) +
  geom_bar(aes(y = node_name, x = datasets, fill = category), stat = "identity") +
  scale_fill_manual(values = c("#7ABD7E", "#FFB54C", "#FF6961")) +
  scale_x_continuous(
    labels = label_comma()
  ) +
  ylab("node") +
  ggtitle("Number of datasets by node and license") +
  report_theme
```